### ISSUE TITLE
How kmstool-enclave-cli  decrypt a cipher text with an Asymmetric key?

### ISSUE THREAD

**Issue by Allen-yan** [aws/aws-nitro-enclaves-sdk-c#69]
Currently, this tools can generateDataKey with a symmetric key.  Then decrypt the data key with the symmetric key.

I want to encrypt and decrypt with an asymmetric key. 
Is it possible for kmstool-enclave-cli to do that?

**Comment by alcioa** [comment]
Hi, asymmetric keys are usually used for enveloping other data keys. However, if you have small payloads which meet the asymmetric key requirements then see [here](https://docs.aws.amazon.com/kms/latest/developerguide/asymm-create-key.html) how to create KMS asymmetric keys.

Another option is to use the actual aws libcrypto the SDK uses as backend and generate a RSA/EC keypair and then encrypt somewhere outside the enclave and decrypt inside the enclave. See [here](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/attestation.c#L30) an example how we generate an asymmetric keypair inside the enclave.

**Comment by Allen-yan** [comment]
Thanks your reply @alcioa .

Yes, I just want to encrypt/decrypt a ethereum account private key in enclave. I know how to create an asymmetric keys in KMS or by the  libcrypto .  I want kms to hold my private key.

If I generate an asymmetric inside the enclave , where does the private key save?

**Comment by Allen-yan** [comment]
I'm not familiar with the C program language.

So I just want to add some changes to the codes in this project to make the kmstool-enclave-cli to support the decrypt method with asymmetric keys. I not quite sure if this changes can work.

1. add the "aws-key-id" parameter in request https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/bin/kmstool-enclave-cli/main.c
2. change the default  request's encryption algorithm from SYMMETRIC_DEFAULT to AWS_EA_RSAES_OAEP_SHA_256
request_structure->encryption_algorithm = AWS_EA_RSAES_OAEP_SHA_256;

**Comment by alcioa** [comment]
@Allen-yan if you generate a keypair inside the enclave, it stays in the enclave. See [here](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/attestation.c#L30). If you look at the [decrypt](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/include/aws/nitro_enclaves/kms.h#L972) function, it does what you need to, with the only difference is that it uses the internal asymmetric key used for enclave attestation.

So one way would be to add another similar API to include `const struct aws_string *key_id` as KMS key ID parameter (which you used to encrypt somewhere your data that you decrypt inside the enclave). Also internal modifications are needed in order to not use the internal KMS client asymmetric keypair and just talk with KMS and decrypt your data. That is if you use KMS keys.

The encryption function is already [there](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/include/aws/nitro_enclaves/kms.h#L988).

Let me know if this answers your questions.

**Comment by Allen-yan** [comment]
@alcioa I have done the decrypt function. The ciphertext_decrypted has been encode to base64 . So I drop the part in main.c
`/* Encode ciphertext into base64 for printing out the result. */`

But how to make the aws_byte_buf as the output directly?

**Comment by alcioa** [comment]
@Allen-yan here is an [example](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/bin/kmstool-enclave/main.c#L322)

**Comment by alcioa** [comment]
@Allen-yan did that help? Do you get the decrypted ciphertext in the byte buff in your application?

**Comment by Allen-yan** [comment]
@alcioa  Thanks! I have done the job
