### ISSUE TITLE
How to request an attestation document ?

### ISSUE THREAD

**Issue by msnitish** [aws/aws-nitro-enclaves-sdk-c#70]
In the [AWS documentation for Nitro Enclaves](https://docs.aws.amazon.com/enclaves/latest/user/set-up-attestation.html#:~:text=get%2Dattestation%2Ddocument%20API), It is mentioned that :

> You can request an enclave's attestation document from inside the enclave only, using the `get-attestation-document` API, which is included in the Nitro Enclaves SDK.

In the docs folder of this repository, I could not find any documentation explaining about the  `get-attestation-document` API.
Could documentation for this API too be added ?

**Comment by alcioa** [comment]
@msnitish [here](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/include/aws/nitro_enclaves/attestation.h#L64) is the API that you can use to retrieve the attestation document. Notice the output parameter. [This](https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/kms.c#L2627) is how decrypt invokes it. 

We also have two samples here for Python and Rust on how to retrieve it without the SDK via the NSM API directly.

**Comment by richardfan1126** [comment]
@msnitish 

First, create a keypair by calling `aws_attestation_rsa_keypair_new` like this: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/56fe8a7ea672933f0465ec16076654d9487adcb1/source/kms.c#L2503

It will return a `struct aws_rsa_keypair` variable

Then pass the keypair to a function `aws_attestation_request` like this: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/56fe8a7ea672933f0465ec16076654d9487adcb1/source/kms.c#L2627-L2628

The attestation document will be allocated in the variable passed as the 3rd parameter, which is a `struct aws_byte_buf`

---

The `get-attestation-document` API is actually not in this SDK. The documentations on Nitro Enclave is quite messy

It's in the NSM API https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/nsm-lib/src/lib.rs#L217

**Comment by richardfan1126** [comment]
@msnitish 

You can reference `kms.c` on how to use this SDK to generate an attestation document

First, create a keypair using `aws_attestation_rsa_keypair_new` like: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/kms.c#L2503

Then pass the keypair into `aws_attestation_request` to generate the attestation document like: https://github.com/aws/aws-nitro-enclaves-sdk-c/blob/main/source/kms.c#L2627-L2628

---

But I would recommend you to use the NSM API directly because the function written in this SDK is not quite aligned with the original NSM API.

Like @alcioa said, you can write your own Rust program to use the function exposed by https://github.com/aws/aws-nitro-enclaves-nsm-api
Or you can even rewrite the nsm-lib to make it usable in Python, like this one: https://github.com/donkersgoed/aws-nitro-enclaves-nsm-api/commit/112a450082d108bf466ca57e687beaaeff19db4a

I have sample code on how I use this rewritten library to generate attestation document:
https://dev.to/aws-builders/how-to-use-aws-nitro-enclaves-attestation-document-2376
https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier

**Comment by nitish-at** [comment]
@alcioa Thank you for sharing the function which can generate the attestation document.
The return value of the function `aws_attestation_request`  seems to have an `int` data type whereas in [this document](https://docs.aws.amazon.com/enclaves/latest/user/verify-root.html#enclave-attestation),
the structure of attestation is described as :

>  The attestation document that is generated by the Nitro system is encoded in Concise Binary Object Representation (CBOR)

Since, CBOR is not just an `int` type, what am I am missing ? 
Is the function return value of `aws_attestation_request`  a value similar to boolean value (0 or 1) ?

**Comment by msnitish** [comment]
@alcioa Thank you for sharing the function which can generate the attestation document.
The return value of the function `aws_attestation_request`  seems to have an `int` data type whereas in [this document](https://docs.aws.amazon.com/enclaves/latest/user/verify-root.html#enclave-attestation),
the structure of attestation is described as :
>  The attestation document that is generated by the Nitro system is encoded in Concise Binary Object Representation (CBOR)

Since, CBOR is not just an `int` type, what am I am missing ?
Is the function return value of `aws_attestation_request`  a value similar to boolean value (0 or 1) ?

**Comment by richardfan1126** [comment]
@msnitish 
The return value is the return code, 0 means success, other value mean fail.

The document is in the variable you pass in the 3rd parameter

**Comment by msnitish** [comment]
@richardfan1126 

I am assuming that the application which you've written [[https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier](https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier)], explains about the process for the enclave to attest with it's parent instance.

I would like to know about the process of remote attestation of the enclave. 
If there is an instance other than parent instance, how can the Enclave prove it's identity with that foreign instance to exchange data or communicate ?

**Comment by richardfan1126** [comment]
@msnitish 

You can verify the source of the attestation document using the PCR data https://docs.aws.amazon.com/enclaves/latest/user/set-up-attestation.html

If you want to verify which instance generates the document, you can check the PCR4 value

**Comment by alcioa** [comment]
@msnitish is there any more info needed here?

**Comment by msnitish** [comment]
@alcioa , @richardfan1126  Thank you for the support. Please consider this issue resolved.
